"use client"

import './globals.css'
import { Provider } from 'react-redux'
import { store } from '@/store/store'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Nav from '@/components/Nav';

export const metadata = {
  title: 'TMDB',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Provider store={store}>
          <Nav/>
          {children}
          <ToastContainer />
      </Provider>
      </body>
    </html>
  )
}
